### ISSUE TITLE
Wrong path in stack traces with source maps

### ISSUE THREAD

**Issue by gear54rus** [gear54rus/aps-node-runtime#21]
For some reason, the path is mangled. Stack trace for `endpoint.js`:

```
2016-01-11 23:11:04.152 [ERROR][E:5de] Failed to initialize: Error: test
    at ../../_src/runtime/endpoint.js:97:13
    at tryCatcher (/usr/share/aps/node/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/share/aps/node/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/share/aps/node/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/share/aps/node/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/share/aps/node/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/usr/share/aps/node/node_modules/bluebird/js/release/promise.js:615:18)
    at /usr/share/aps/node/node_modules/bluebird/js/release/nodeback.js:42:21
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Notice that other paths are OK. Source map in question:

    {"version":3,"sources":["../../_src/runtime/endpoint.js"],"names":[],"mappings":"...

Need to research the `sourceFileName` from [these docs](https://babeljs.io/docs/usage/options/).

**Comment by gear54rus** [comment]
IDK how it works, seriously... Not sure `source-map-support` even supports relative paths. It seems to just dump whatever's in `sources[0]` in that trace, even if it's a relative path. Found [this](https://github.com/evanw/node-source-map-support/issues/120).

Also, `babel` compilation step when building may have to be done separately for each file because no relative directories change the generated path in `sources[0]`... Send help. :grinning:
